minor fix

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -245,8 +245,12 @@ jobs:
             patch -p1 < fix.patch
             
           else
-            echo "Invalid KernelSU variant selected!"
-            exit 1
+            echo "Applying SUSFS patches for KernelSU-Next..."
+            cd ./KernelSU-Next
+            cp ../../kernel_patches/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./
+            patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
+            # echo "Invalid KernelSU variant selected!"
+            # exit 1
           fi
 
           # Change to common directory and apply common SUSFS patch
