default to "next" branch

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -185,8 +185,9 @@ jobs:
           elif [[ "${{ inputs.kernelsu_branch }}" == "Other" && -n "${{ inputs.kernelsu_branch_other }}" ]]; then
             echo "BRANCH=-s ${{ inputs.kernelsu_branch_other }}" >> $GITHUB_ENV
           else
-            echo "Error: Custom branch not provided for 'Other'" >&2
-            exit 1
+            echo "BRANCH=-s next" >> $GITHUB_ENV
+            # echo "Error: Custom branch not provided for 'Other'" >&2
+            # exit 1
           fi
       
       - name: Add KernelSU
